### ISSUE TITLE
Error in Pre-reqs index.Rmd

### ISSUE THREAD

**Issue by zalmquist** [hanowell/uwsoc533a#28]
You have pre-req error (CS&SS/SOC/STAT 563: Statistical Demography & Data Science is set up as follow up to SOC 533 and is taught by Adrian Raftery). We are requiring familiarity with R at the is level (https://clanfear.github.io/CSSS508/docs/syllabus.html) and expect student to have had statistics at (https://soc.washington.edu/courses/2020/spring/soc/506/a SOC 506/ CSSS 507) and we want to add the Co-Req of CSDE 502 R Lab for Demography.

**Comment by zalmquist** [comment]
You have pre-req error (CS&SS/SOC/STAT 563: Statistical Demography & Data Science is set up as follow up to SOC 533 and is taught by Adrian Raftery). We are requiring familiarity with R at the is level (https://clanfear.github.io/CSSS508/docs/syllabus.html) and expect student to have had statistics at (https://soc.washington.edu/courses/2020/spring/soc/506/a SOC 506/ CSSS 507) and we want to add the Co-Req of CSDE 502 R Lab for Demography.

**Comment by hanowell** [comment]
Thanks, @zalmquist, I will fix this in the syllabus. In addition, I have notified the registrar (see our previous email thread).

**Comment by hanowell** [comment]
Fixed in https://github.com/hanowell/uwsoc533a/commit/fd97bbd879925b16f87cf08c75afbfc47f78d595
